### ISSUE TITLE
Add more detail about EALSTM train/test split

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/lake-temp-lstm-static-data-release#67]
From Sam:

> How was the 60% train/40% test determined? By lake? Temporally?

**Comment by AndyMcAliley** [comment]
By lake. The process description does state this: "Data were split by lake to avoid data leakage."

We could expound: 

"In order to determine the split, data were grouped by lake, and each lake was randomly assigned to one of the three splits in such a way that the desired data proportions were achieved. Data were split by lake in this way to ensure that the test set could be used to evaluate model performance on unobserved lakes."

**Comment by lindsayplatt** [comment]
@AndyMcAliley yes, let's just add that additional content. Can you PR that addition to this section? https://github.com/USGS-R/lake-temp-lstm-static-data-release/blob/main/in_text/text_data_release.yml#L2058
