### ISSUE TITLE
Zenodo?

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/lake-temp-lstm-static-data-release#69]

**Comment by lindsayplatt** [comment]
See Sam's comments in MS doc.

**Comment by jzwart** [comment]
high priority. This is relatively easy and doesn't require IPDS record because you can use provisional software release guidance from FSP. Just need to create a tag of relevant repos and either download the zip / tarball or integrate into zenodo. I can help out with this. I'd estimate this would take less than 1 hour to do and would allow you to point to it for processing descriptions

**Comment by lindsayplatt** [comment]
Determined to be not a viable option for us at this time. Closing and commenting more details in the reconciliation document.
